package com.racetimer.pairskew.analysis

import com.racetimer.pairskew.protocol.Primitive
import com.racetimer.pairskew.protocol.Record
import com.racetimer.pairskew.protocol.Side
import com.racetimer.pairskew.protocol.floorMs
import java.util.Locale
import kotlin.math.abs
import kotlin.math.ceil

/** The capture as Markdown: the raw material for docs/pair-skew.md, not the write-up itself. */
class Report(private val a: Analysis) {

    private val capture = a.capture
    private val rounds = a.rounds

    fun markdown(): String = buildString {
        appendLine("# PairSkew capture report")
        appendLine()
        appendLine(
            "Generated by `harness/pair-skew/analysis` from ${capture.records.size} distinct records. θ is the " +
                "watch's clock minus the phone's. Every offset and bound is #217's translateGun, over rounds " +
                "floored to whole milliseconds as production reads them, at a stated drift of ${a.ppm} ppm " +
                "unless a column says otherwise.",
        )
        appendLine()
        if (rounds.isEmpty()) {
            appendLine("**No completed rounds.** ${capture.failures.size} failures.")
            failureReasons()
            return@buildString
        }
        instruments()
        session()
        timeline()
        roundTrips()
        scatter()
        drift()
        bursts()
        gaps()
        guns()
    }

    private fun StringBuilder.instruments() {
        appendLine("## Instruments")
        appendLine()
        table(
            listOf("side", "maker", "model", "sdk", "app", "version", "run"),
            capture.hellos.map { h -> listOf(h["side"], h["maker"], h["model"], h["sdk"], h["app"], h["ver"], h["run"]).map { it ?: "-" } },
        )
    }

    private fun StringBuilder.session() {
        val spanMin = (rounds.last().phoneAtNs - rounds.first().phoneAtNs) / 6e10
        appendLine("## Session")
        appendLine()
        appendLine("- Completed rounds: **${rounds.size}** over ${f1(spanMin)} min of phone clock; ${capture.late.size} of them answered after their timeout.")
        appendLine("- Failed rounds: **${capture.failures.size}**.")
        for (side in Side.entries) {
            val mine = rounds.filter { it.requester == side }
            if (mine.isNotEmpty()) appendLine("- Asked by the ${side.wire}: ${mine.size} (${mine.count { it.primitive == Primitive.MSG }} message pairs, ${mine.count { it.primitive == Primitive.RPC }} requests).")
        }
        appendLine()
        failureReasons()
    }

    private fun StringBuilder.failureReasons() {
        if (capture.failures.isEmpty()) return
        appendLine("Failures by reason and transport:")
        appendLine()
        val rows = capture.failures.groupBy { Triple(it["reason"] ?: "-", it["near"] ?: "-", it["prim"] ?: "-") }
            .entries.sortedByDescending { it.value.size }
            .map { (key, list) -> listOf(key.first, nearLabel(key.second), key.third, "${list.size}") }
        table(listOf("reason", "peer", "primitive", "count"), rows)
    }

    private fun StringBuilder.timeline() {
        appendLine("## Timeline")
        appendLine()
        appendLine("Per minute of phone clock from the first round. `bt` is each device's own Bluetooth adapter at the minute's end.")
        appendLine()
        val t0 = rounds.first().phoneAtNs
        val minuteOf = { ns: Long -> Math.floorDiv(ns - t0, 60_000_000_000L).toInt() }
        val last = minuteOf(rounds.last().phoneAtNs)
        val fails = capture.failures.groupBy { minuteOf(a.phoneNs(Side.of(it.text("req")), it.long("at"))) }
        val links = capture.links.map { minuteOf(a.phoneNs(it)) to it }.sortedBy { it.first }
        val rows = (0..last).map { m ->
            val these = rounds.filter { minuteOf(it.phoneAtNs) == m }
            val near = these.count { it.nearby == true }
            val btAt = { side: String -> links.lastOrNull { it.first <= m && it.second["side"] == side }?.second?.get("bt") ?: "-" }
            listOf(
                "$m",
                "${these.size}",
                "${fails[m]?.size ?: 0}",
                if (these.isEmpty()) "-" else "$near/${these.size}",
                if (these.isEmpty()) "-" else f1(quantile(these.map { it.rttNs / 1e6 }, 0.5)),
                btAt("phone"),
                btAt("wear"),
            )
        }
        table(listOf("min", "ok", "fail", "nearby", "median RTT ms", "phone bt", "watch bt"), rows)
    }

    private fun StringBuilder.roundTrips() {
        appendLine("## Round trips and single-round bounds")
        appendLine()
        appendLine(
            "A single round's bound is what translateGun reports from that round alone, at the instant it was " +
                "measured: half the round trip, plus the 1 ms read resolution each side, plus drift over the round.",
        )
        appendLine()
        val groups = rounds.groupBy { Triple(it.transport(), it.primitive, it.requester) }.toSortedMap(compareBy({ it.first }, { it.second }, { it.third }))
        val rows = groups.map { (key, members) ->
            val rtt = members.map { it.rttNs / 1e6 }
            val bounds = members.mapNotNull { r ->
                val atMs = floorMs(r.phoneAtNs)
                translateAt(atMs, listOf(r.phoneFrameMs()), a.ppm).estimateAt(atMs)?.boundMs?.toDouble()
            }
            val failed = capture.failures.count {
                it["near"] == wireNear(key.first) && it["prim"] == key.second.wire && it["req"] == key.third.wire
            }
            listOf(
                key.first.label, key.second.wire, key.third.wire, "${members.size}", "$failed",
                f1(rtt.min()), f1(quantile(rtt, 0.5)), f1(quantile(rtt, 0.9)), f1(rtt.max()),
                if (bounds.isEmpty()) "-" else f0(quantile(bounds, 0.5)),
                if (bounds.isEmpty()) "-" else f0(bounds.max()),
            )
        }
        table(listOf("transport", "primitive", "asked by", "ok", "fail", "RTT min", "RTT median", "RTT p90", "RTT max", "bound median", "bound max"), rows)
    }

    private fun StringBuilder.scatter() {
        appendLine("## Scatter against the neighbours")
        appendLine()
        appendLine(
            "Each round's own midpoint against the intersection of every *other* round within ${a.windowMs / 1000} s. " +
                "This measures scatter, not truth: a delay that is always longer one way than the other moves every " +
                "midpoint alike, and only the bound covers it. A contradiction is two sound intervals that fail to " +
                "overlap, which should never happen and would mean a bad stamp or a drift faster than the stated rate.",
        )
        appendLine()
        val rows = a.judged.groupBy { it.round.transport() }.toSortedMap().map { (transport, js) ->
            val withRef = js.filter { it.reference != null }
            val err = withRef.map { abs(it.errorMs!!).toDouble() }
            val refBound = withRef.map { it.reference!!.boundMs.toDouble() }
            listOf(
                transport.label, "${js.size}", "${withRef.size}",
                if (err.isEmpty()) "-" else f0(quantile(err, 0.5)),
                if (err.isEmpty()) "-" else f0(quantile(err, 0.9)),
                if (err.isEmpty()) "-" else f0(err.max()),
                if (refBound.isEmpty()) "-" else f0(quantile(refBound, 0.5)),
                "${js.count { it.contradicts }}",
                "${js.count { it.referenceInconsistent }}",
            )
        }
        table(listOf("transport", "rounds", "with a reference", "|error| median", "p90", "max", "reference bound median", "contradictions", "inconsistent references"), rows)
        val worst = a.judged.filter { it.errorMs != null }.sortedByDescending { abs(it.errorMs!!) }.take(5)
        if (worst.isNotEmpty()) {
            appendLine("Largest scatter:")
            appendLine()
            table(
                listOf("at min", "transport", "prim", "asked by", "RTT ms", "error ms", "own bound", "reference bound"),
                worst.map { j ->
                    listOf(
                        f1((j.round.phoneAtNs - rounds.first().phoneAtNs) / 6e10), j.round.transport().label, j.round.primitive.wire,
                        j.round.requester.wire, f1(j.round.rttNs / 1e6), "${j.errorMs}", "${j.own.boundMs}", "${j.reference!!.boundMs}",
                    )
                },
            )
        }
    }

    private fun StringBuilder.drift() {
        appendLine("## Relative drift")
        appendLine()
        val d = a.drift
        if (d == null) {
            appendLine("Too few rounds to fit.")
            appendLine()
            return
        }
        appendLine(
            "Fitted to ${d.n} ${d.basis}, over ${f1(d.spanMin)} min: **${f1(d.ppm)} ppm** " +
                "(±${f1(2 * d.ppmStdErr)} at two standard errors), residual RMS ${f1(d.residualRmsMs)} ms. " +
                "Positive means the watch's clock runs fast against the phone's.",
        )
        appendLine()
    }

    private fun StringBuilder.bursts() {
        appendLine("## Bursts: what a production link would report")
        appendLine()
        appendLine(
            "A burst is ${com.racetimer.pairskew.protocol.Harness.BURST_SIZE} rounds back to back. Its bound is translateGun " +
                "over that burst's rounds alone, for a gun at the burst's end (`@0`) or a minute or five later, aged " +
                "at ${a.ppm} ppm. `last 60 s` is every round of the minute before the burst's end, which is what a link " +
                "that keeps its rounds gets.",
        )
        appendLine()
        val clean = a.bursts.filter { it.transport != null }
        val rows = clean.groupBy { it.transport!! }.toSortedMap().map { (transport, bs) ->
            val at0 = bs.mapNotNull { a.burstBound(it, 0L)?.toDouble() }
            val at1 = bs.mapNotNull { a.burstBound(it, 60_000L)?.toDouble() }
            val at5 = bs.mapNotNull { a.burstBound(it, 300_000L)?.toDouble() }
            val look = bs.mapNotNull { a.lookbackBound(it, 60_000L)?.toDouble() }
            listOf(
                transport.label, "${bs.size}",
                q(at0, 0.5), q(at0, 0.9), q(at0, 1.0),
                q(at1, 1.0), q(at5, 1.0),
                q(look, 0.5), q(look, 1.0),
            )
        }
        table(listOf("transport", "bursts", "@0 median", "@0 p90", "@0 max", "@1 min max", "@5 min max", "last 60 s median", "last 60 s max"), rows)
        val mixed = a.bursts.size - clean.size
        if (mixed > 0) {
            appendLine("$mixed burst(s) changed transport partway and are left out above.")
            appendLine()
        }
        val t0 = rounds.first().phoneAtNs
        val wide = clean.filter { it.transport == Transport.BLUETOOTH }
            .mapNotNull { b -> a.burstBound(b, 0L)?.let { b to it } }
            .filter { (_, bound) -> bound > WIDE_BURST_MS }
        if (wide.isNotEmpty()) {
            appendLine("Bluetooth bursts whose bound at the burst exceeds $WIDE_BURST_MS ms, and why: their slowest round.")
            appendLine()
            table(
                listOf("at min", "asked by", "rounds", "late rounds", "slowest RTT ms", "bound ms"),
                wide.map { (b, bound) ->
                    listOf(
                        f1((b.rounds.minOf { it.phoneAtNs } - t0) / 6e10), b.requester.wire, "${b.rounds.size}",
                        "${b.rounds.count { Triple(it.requester, it.run, it.id) in capture.late }}",
                        f0(b.rounds.maxOf { it.rttNs } / 1e6), "$bound",
                    )
                },
            )
        }
        budgetTable(clean)
        appendLine("Aging alone, `ceil(ppm × Δt)` ms, which translateGun adds to every round's interval:")
        appendLine()
        val spans = listOf(60_000L, 300_000L, 600_000L)
        table(
            listOf("stated ppm") + spans.map { "${it / 60_000} min" },
            listOf(10L, 25L, 50L, 100L).map { p -> listOf("$p") + spans.map { "${ceil(p * it / 1e6).toLong()}" } },
        )
    }

    private fun StringBuilder.budgetTable(clean: List<Analysis.Burst>) {
        appendLine("Share of bursts whose bound fits each candidate budget. No budget is chosen here; D2 is the owner's.")
        appendLine()
        val budgets = listOf(10L, 20L, 30L, 50L, 75L, 100L, 150L, 200L)
        val byTransport = clean.groupBy { it.transport!! }.toSortedMap()
        val header = listOf("budget ms") + byTransport.keys.flatMap { t -> listOf("${t.label} @0", "@1 min", "@5 min") }
        val rows = budgets.map { budget ->
            listOf("$budget") + byTransport.values.flatMap { bs ->
                listOf(0L, 60_000L, 300_000L).map { ahead ->
                    val bounds = bs.mapNotNull { a.burstBound(it, ahead) }
                    pct(bounds.count { it <= budget }, bounds.size)
                }
            }
        }
        table(header, rows)
    }

    private fun StringBuilder.gaps() {
        appendLine("## Link gaps")
        appendLine()
        if (a.gaps.isEmpty()) {
            appendLine("No stretch of more than ${Analysis.GAP_NS / 1_000_000_000} s without a completed round.")
            appendLine()
            return
        }
        appendLine(
            "Each stretch of more than ${Analysis.GAP_NS / 1_000_000_000} s with no completed round. θ before and after come from " +
                "the minute of rounds on each side. The jump is how far the offset moved across the gap, against what the " +
                "fitted drift predicts for its length.",
        )
        appendLine()
        val t0 = rounds.first().phoneAtNs
        val d = a.drift
        val rows = a.gaps.mapIndexed { i, gap ->
            val (before, after) = a.edges(gap)
            val startNs = gap.before.phoneAtNs
            val endNs = gap.after.phoneAtNs
            val failed = capture.failures.count { a.phoneNs(Side.of(it.text("req")), it.long("at")) in startNs..endNs }
            val jump = if (before != null && after != null) after.offsetMs - before.offsetMs else null
            listOf(
                "${i + 1}", f1((startNs - t0) / 6e10), f1((endNs - t0) / 6e10), f1(gap.durationMs / 1000.0), "$failed",
                before?.let { "± ${it.boundMs}" } ?: "-", after?.let { "± ${it.boundMs}" } ?: "-",
                jump?.toString() ?: "-",
                d?.let { f1(it.ppm * gap.durationMs / 1e6) } ?: "-",
            )
        }
        table(listOf("gap", "from min", "to min", "seconds", "failed rounds", "θ before", "θ after", "jump ms", "drift predicts ms"), rows)
        for ((i, gap) in a.gaps.withIndex()) retention(i + 1, gap)
    }

    /** What each side logged about the offset it held while no round could complete. */
    private fun StringBuilder.retention(n: Int, gap: Analysis.Gap) {
        val startNs = gap.before.phoneAtNs
        val endNs = gap.after.phoneAtNs
        val inside = capture.states.filter { a.phoneNs(it) in startNs..endNs }
        if (inside.isEmpty()) return
        appendLine("Gap $n, what each side held with no exchange (`STATE` lines inside the gap):")
        appendLine()
        val rows = inside.groupBy { it["side"] ?: "-" }.map { (side, states) ->
            val offsets = states.mapNotNull { it["offset_ms"]?.toLongOrNull() }
            listOf(
                side, "${states.size}",
                states.first()["samples"] ?: "-", states.last()["samples"] ?: "-",
                if (offsets.isEmpty()) "-" else "${offsets.max() - offsets.min()}",
                states.first()["bound_ms"] ?: "-", states.last()["bound_ms"] ?: "-",
                states.last()["age_ms"] ?: "-",
                states.mapNotNull { it["result"] }.distinct().joinToString("/"),
            )
        }
        table(listOf("side", "STATE lines", "samples first", "samples last", "offset spread ms", "bound first", "bound last", "age at last ms", "result"), rows)
    }

    private fun StringBuilder.guns() {
        appendLine("## Guns")
        appendLine()
        val byGun = capture.guns.filter { it["gun"] != null }.groupBy { it.text("gun") }
        if (byGun.isEmpty()) {
            appendLine("No gun was armed.")
            appendLine()
            return
        }
        appendLine(
            "The arming side holds the gun on its own clock. The other side adopts translateGun's answer once and " +
                "holds it, logging what a fresh translation would say after every round. Skew is the adopted gun " +
                "against a fresh estimate from the rounds within ${a.windowMs / 1000} s of the gun, with that estimate's bound.",
        )
        appendLine()
        for ((id, recs) in byGun) {
            val armed = recs.firstOrNull { it["event"] == "armed" }
            val adopted = recs.firstOrNull { it["event"] == "adopted" }
            val retranslated = recs.filter { it["event"] == "retranslated" && it["moved_ms"] != null }
            val fired = recs.filter { it["event"] == "fired" }
            appendLine("### Gun `$id`")
            appendLine()
            appendLine("- Armed on the ${armed?.get("side") ?: "?"} at its ${armed?.get("src_ms") ?: "?"} ms.")
            if (adopted == null) {
                appendLine("- Never adopted: ${recs.filter { it["event"] == "unsent" }.joinToString { it["reason"] ?: "-" }.ifEmpty { "no record" }}.")
            } else {
                appendLine(
                    "- Adopted by the ${adopted["side"]} from ${adopted["n"]} rounds: ${adopted["result"]}, " +
                        "held at ${adopted["own_ms"] ?: "-"} ms ± ${adopted["bound_ms"] ?: "-"} ms.",
                )
            }
            if (retranslated.isNotEmpty()) {
                val moved = retranslated.map { it.long("moved_ms") }
                appendLine(
                    "- Re-translated ${retranslated.size} times after adoption: moved ${moved.min()}..${moved.max()} ms, " +
                        "last ± ${retranslated.last()["bound_ms"]} ms from ${retranslated.last()["n"]} rounds.",
                )
            }
            for (f in fired) appendLine("- Fired on the ${f["side"]}: ${f["late_ms"]} ms after its own instant.")
            skewAtGun(armed, adopted)
            appendLine()
        }
    }

    private fun StringBuilder.skewAtGun(armed: Record?, adopted: Record?) {
        if (armed == null || adopted == null || adopted["own_ms"] == null) return
        val src = Side.of(armed.text("side"))
        val srcMs = armed.long("src_ms")
        val heldMs = adopted.long("own_ms")
        // θ at the gun, as a phone-clock instant: the phone's own reading, or the watch's held one moved.
        val phoneMs = if (src == Side.PHONE) srcMs else heldMs
        val fresh = a.freshAt(phoneMs) ?: run {
            appendLine("- No fresh estimate at the gun: no rounds within ${a.windowMs / 1000} s of it.")
            return
        }
        // Where a fresh exchange puts the gun on the adopting side's clock.
        val freshHeldMs = if (src == Side.PHONE) srcMs + fresh.offsetMs else srcMs - fresh.offsetMs
        appendLine(
            "- **Skew at the gun: ${heldMs - freshHeldMs} ms** (held against fresh), the fresh estimate good to ± ${fresh.boundMs} ms; " +
                "the adopted bound was ± ${adopted["bound_ms"]} ms.",
        )
    }

    // --- formatting -------------------------------------------------------------------------------

    private fun StringBuilder.table(header: List<String>, rows: List<List<String>>) {
        appendLine("| " + header.joinToString(" | ") + " |")
        appendLine("|" + header.joinToString("|") { "---" } + "|")
        for (row in rows) appendLine("| " + row.joinToString(" | ") + " |")
        appendLine()
    }

    private fun q(values: List<Double>, q: Double): String = if (values.isEmpty()) "-" else f0(quantile(values, q))
    private fun f0(x: Double): String = String.format(Locale.US, "%.0f", x)
    private fun f1(x: Double): String = String.format(Locale.US, "%.1f", x)
    private fun pct(k: Int, n: Int): String = if (n == 0) "-" else String.format(Locale.US, "%.0f%%", 100.0 * k / n)

    private fun nearLabel(wire: String): String = when (wire) {
        "1" -> Transport.BLUETOOTH.label
        "0" -> Transport.CLOUD.label
        else -> "no peer"
    }

    private fun wireNear(t: Transport): String = when (t) {
        Transport.BLUETOOTH -> "1"
        Transport.CLOUD -> "0"
        Transport.UNKNOWN -> "-"
    }

    private companion object {
        /** The epic's candidate budget: the line past which a burst's miss is worth explaining. */
        const val WIDE_BURST_MS = 100L
    }
}
