#!/usr/bin/env python3
"""Build the publishable privacy-policy site from docs/privacy-policy.md.

The published branch holds this output and nothing else. That is the whole safety model: the branch
is a whitelist by construction, so no document can reach the public site by being dropped into a
folder. docs/ carries the Google account address, the signing procedure and the watch's pairing
address -- all already visible in a public repo, but a rendered, search-indexed page is a different
thing from a file in a git tree, and that is exactly how the pairing address ended up online.

Run by the publish workflow on every change to the policy, and by hand for the first publish, so the
two cannot diverge.

    python .github/scripts/build-privacy-page.py <output-dir>

Every transform asserts its own precondition. Stripping the maintainer block by a pattern that
matched nothing would publish the block, and the failure would be silent -- the page would render
fine, because the block is an HTML comment and browsers do not draw it.
"""

import re
import shutil
import sys
from pathlib import Path

SOURCE = Path("docs/privacy-policy.md")

# The canonical URL. Play fetches this, and a dead policy URL is grounds for removal, so it is
# quoted here as the one place the path is written down outside the issue.
CANONICAL = "https://sailordave17.github.io/race-timer/privacy-policy"

CONFIG = """\
# The site that serves the privacy policy, and nothing else.
#
# GENERATED by .github/scripts/build-privacy-page.py -- do not hand-edit this branch. Every file
# here is overwritten on the next publish, so an edit made in place is lost without a warning.
title: Mad Cow Race Timer
description: Privacy policy for Mad Cow Race Timer, a sailing start-sequence timer for Wear OS and Android phones.
theme: jekyll-theme-primer
"""

INDEX = """\
---
description: Mad Cow Race Timer, a sailing start-sequence timer for Wear OS and Android phones.
---

# Mad Cow Race Timer

A start-sequence timer for sailboat racing. It runs standalone on a Wear OS watch, with no phone
required on the water, and standalone on an Android phone for the committee-boat console.

- [Privacy policy](privacy-policy) -- the app collects no data at all
- [Source code](https://github.com/SailorDave17/race-timer)

This site exists to host the privacy policy at a stable address. It is deliberately not the
project's documentation, which lives in the repository.
"""

FRONT_MATTER = """\
---
description: >-
  Privacy policy for Mad Cow Race Timer, a sailing start-sequence timer that runs standalone on
  Wear OS watches and on Android phones. The app collects no personal data, has no network
  access, and transmits nothing.
---

"""


def strip_maintainer_block(text):
    """Remove the trailing maintainer comment, failing loudly if it is not where it should be."""
    pattern = re.compile(r"\n?<!--\s*\nMAINTAINER NOTES.*?-->\s*\n?", re.DOTALL)
    stripped, count = pattern.subn("\n", text)
    if count != 1:
        raise SystemExit(
            f"expected exactly 1 maintainer block in {SOURCE}, found {count} -- refusing to publish"
        )
    if "MAINTAINER" in stripped:
        raise SystemExit("maintainer text survived the strip -- refusing to publish")
    # The block is the only HTML comment in the file; anything left is unexpected and worth a stop.
    if "<!--" in stripped:
        raise SystemExit("an HTML comment survived the strip -- refusing to publish")
    return stripped.rstrip() + "\n"


def main():
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    out = Path(sys.argv[1])

    if not SOURCE.exists():
        raise SystemExit(f"{SOURCE} not found -- run this from the repository root")

    policy = strip_maintainer_block(SOURCE.read_text(encoding="utf-8"))

    # A published policy that does not say when it took effect is not a policy Play will accept,
    # and the placeholder is easy to leave behind.
    if "Effective date:" not in policy:
        raise SystemExit("the policy has no effective date -- refusing to publish")

    if out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True)

    (out / "_config.yml").write_text(CONFIG, encoding="utf-8")
    (out / "index.md").write_text(INDEX, encoding="utf-8")
    (out / "privacy-policy.md").write_text(FRONT_MATTER + policy, encoding="utf-8")

    print(f"built {out}/ from {SOURCE}")
    print(f"  canonical URL: {CANONICAL}")
    for f in sorted(out.iterdir()):
        print(f"  {f.name:20} {f.stat().st_size:>6} bytes")


if __name__ == "__main__":
    main()
